Importing libraries pandas, numpy, matplotlib

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("./northwind_order_details.csv")
df.head(5)

   order_id  product_id  unit_price  quantity  discount
0     10248          11        14.0        12       0.0
1     10248          42         9.8        10       0.0
2     10248          72        34.8         5       0.0
3     10249          14        18.6         9       0.0
4     10249          51        42.4        40       0.0

In [3]:
df.shape

(2155, 5)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    2155 non-null   int64
 1   product_id  2155 non-null   int64
 2   unit_price  2155 non-null   float64
 3   quantity    2155 non-null   int64
 4   discount    2155 non-null   float64
dtypes: float64(2), int64(3)
memory usage: 84.3 KB

In [5]:
df.describe()

           order_id   product_id   unit_price     quantity     discount
count   2155.000000  2155.000000  2155.000000  2155.000000  2155.000000
mean   10659.375870    40.793039    26.218520    23.812993     0.056167
std      241.378032    22.159019    29.827418    19.022047     0.083450
min    10248.000000     1.000000     2.000000     1.000000     0.000000
25%    10451.000000    22.000000    12.000000    10.000000     0.000000
50%    10657.000000    41.000000    18.400000    20.000000     0.000000
75%    10862.500000    60.000000    32.000000    30.000000     0.100000
max    11077.000000    77.000000   263.500000   130.000000     0.250000

In [6]:
df.isnull().sum()

order_id      0
product_id    0
unit_price    0
quantity      0
discount      0
dtype: int64

In [7]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2150    False
2151    False
2152    False
2153    False
2154    False
Length: 2155, dtype: bool

In [8]:
df.columns

Index(['order_id', 'product_id', 'unit_price', 'quantity', 'discount'], dtype='str')

In [10]:
df.tail()

      order_id  product_id  unit_price  quantity  discount
2150     11077          64       33.25         2      0.03
2151     11077          66       17.00         1      0.00
2152     11077          73       15.00         2      0.01
2153     11077          75        7.75         4      0.00
2154     11077          77       13.00         2      0.00

In [12]:
df.isnull().mean()* 100

order_id      0.0
product_id    0.0
unit_price    0.0
quantity      0.0
discount      0.0
dtype: float64

In [14]:
df.nunique()

order_id      830
product_id     77
unit_price    116
quantity       55
discount       11
dtype: int64

In [22]:
df['quantity'].unique()

array([ 12,  10,   5,   9,  40,  35,  15,   6,  20,  25,  42,  21,  30,
        50,  65,   1,  16,   2,  60,  28,  36,  70,   4,  24,  33,   7,
         8,  18,   3,  45, 100,  14,  80,  48,  56,  13,  77,  54,  55,
        32, 120,  49,  90,  39,  84,  11, 110,  27,  44, 130,  52,  91,
        66,  63,  22])

In [28]:
df['product_id'].max()

np.int64(77)

In [30]:
df.isnull().sum()

order_id      0
product_id    0
unit_price    0
quantity      0
discount      0
dtype: int64

In [33]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2150    False
2151    False
2152    False
2153    False
2154    False
Length: 2155, dtype: bool

In [35]:
df.head(5)

   order_id  product_id  unit_price  quantity  discount
0     10248          11        14.0        12       0.0
1     10248          42         9.8        10       0.0
2     10248          72        34.8         5       0.0
3     10249          14        18.6         9       0.0
4     10249          51        42.4        40       0.0

In [36]:
df.dtypes

order_id        int64
product_id      int64
unit_price    float64
quantity        int64
discount      float64
dtype: object